name: Build

on: push

jobs:
  linux:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: |
        sudo apt-get update
        sudo apt-get install -y libxcb1-dev
    - run: yarn --frozen-lockfile
    - run: yarn build-ts
    - uses: actions/upload-artifact@v1
      with:
        name: linux
        path: prebuilds

